services:
  app:
    network_mode: bridge
    volumes:
      - bin:./bin/
    command: ["./discord_bot"]
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure

volumes:
    - bin
